[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated:Warning
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
