from __future__ import annotations

from typing import Any


EVIDENCE_LEVELS: dict[str, str] = {
    "0": "未出现",
    "1": "出现相关概念",
    "2": "品牌被提及",
    "3": "页面被检索到",
    "4": "页面作为来源被引用",
}


AI_CHANNEL_RULES: list[dict[str, Any]] = [
    {
        "rule_id": "ai-deepseek-rag-001",
        "channel_id": "deepseek",
        "channel_name": "DeepSeek",
        "rule_title": "RAG 友好的自包含内容单元",
        "rule_summary": "面向生成式检索，内容应具备清晰实体、问题答案结构和可独立引用的信息块。",
        "source_type": "legacy_geo_yaml",
        "source_url": "",
        "source_note": "吸收 GEO- backend/data/platform_templates/deepseek.yaml 的设计，P1 仅作 Mock 示例。",
        "knowledge_cutoff": "2026-06",
        "updated_at": "2026-09-09",
        "version": "0.1.0-mock",
        "confidence": 0.72,
        "review_status": "待确认",
        "reviewer": "",
        "effective_status": "草稿",
        "change_log": ["从 GEO- YAML 平台模板抽象为 AIChannelRule。"],
    },
    {
        "rule_id": "ai-doubao-entity-001",
        "channel_id": "doubao",
        "channel_name": "豆包",
        "rule_title": "品牌实体与地域实体一致",
        "rule_summary": "品牌全称、简称、地域、业务类型需要前后一致，避免 AI 难以建立稳定实体关联。",
        "source_type": "manual_research",
        "source_url": "",
        "source_note": "待后续接入真实规则来源与人工复核。",
        "knowledge_cutoff": "待确认",
        "updated_at": "2026-09-09",
        "version": "0.1.0-mock",
        "confidence": 0.55,
        "review_status": "待确认",
        "reviewer": "",
        "effective_status": "草稿",
        "change_log": ["P1 Mock 规则，用于验证规则中心字段。"],
    },
    {
        "rule_id": "ai-yuanbao-source-001",
        "channel_id": "yuanbao",
        "channel_name": "腾讯元宝",
        "rule_title": "来源证据优先",
        "rule_summary": "文章应保留事实来源、页面 URL 和结构化标题，方便后续监测页面检索与来源引用。",
        "source_type": "manual_research",
        "source_url": "",
        "source_note": "待补充官方文档、平台公告或真实测试证据。",
        "knowledge_cutoff": "待确认",
        "updated_at": "2026-09-09",
        "version": "0.1.0-mock",
        "confidence": 0.5,
        "review_status": "待确认",
        "reviewer": "",
        "effective_status": "草稿",
        "change_log": ["P1 Mock 规则，用于验证来源与置信度机制。"],
    },
]


PUBLISHING_CHANNEL_RULES: list[dict[str, Any]] = [
    {
        "rule_id": "pub-wechat-structure-001",
        "channel_id": "wechat_mp",
        "channel_name": "微信公众号",
        "rule_title": "长文结构与品牌专业度",
        "rule_summary": "适合完整知识结构、品牌背书、案例说明和 FAQ，优先保证阅读体验。",
        "source_type": "legacy_geo_publish_adapter",
        "source_url": "",
        "source_note": "吸收 GEO- publish_adapter 的平台改写思路，P1 不做真实发布。",
        "knowledge_cutoff": "2026-06",
        "updated_at": "2026-09-09",
        "version": "0.1.0-mock",
        "confidence": 0.68,
        "review_status": "待确认",
        "reviewer": "",
        "effective_status": "草稿",
        "change_log": ["从旧项目发布适配提示词抽象为 PublishingChannelRule。"],
    },
    {
        "rule_id": "pub-xhs-human-001",
        "channel_id": "xiaohongshu",
        "channel_name": "小红书",
        "rule_title": "场景化表达与弱广告感",
        "rule_summary": "小红书版本需要短段落、场景化、话题标签和更强的人感表达，避免硬广。",
        "source_type": "legacy_geo_platform_rules",
        "source_url": "",
        "source_note": "旧项目 xiaohongshu.json 多处提示信息不足，因此置信度不得设为高。",
        "knowledge_cutoff": "待确认",
        "updated_at": "2026-09-09",
        "version": "0.1.0-mock",
        "confidence": 0.45,
        "review_status": "待确认",
        "reviewer": "",
        "effective_status": "草稿",
        "change_log": ["保留不确定性，后续需要真实平台规则或测试数据校验。"],
    },
    {
        "rule_id": "pub-zhihu-answer-001",
        "channel_id": "zhihu",
        "channel_name": "知乎",
        "rule_title": "问题导向与论证结构",
        "rule_summary": "知乎版本应围绕具体问题展开，包含判断、依据、案例和可验证信息。",
        "source_type": "legacy_geo_publish_adapter",
        "source_url": "",
        "source_note": "吸收旧项目平台改写策略，后续需要补充真实效果数据。",
        "knowledge_cutoff": "2026-06",
        "updated_at": "2026-09-09",
        "version": "0.1.0-mock",
        "confidence": 0.62,
        "review_status": "待确认",
        "reviewer": "",
        "effective_status": "草稿",
        "change_log": ["P1 Mock 规则，用于区分媒体平台与 AI 平台。"],
    },
]


GEO_MONITOR_SESSIONS: list[dict[str, Any]] = [
    {
        "session_id": "geo-mon-p1-mock-001",
        "name": "武汉微艺达智能沙盘 GEO 示例监测",
        "target_brand": "武汉微艺达智能科技有限公司",
        "target_url": "https://example.com/wuhan-sandtable-demo",
        "created_at": "2026-09-09 10:00:00",
        "data_mode": "mock",
        "mock_notice": "示例数据，不计入真实 GEO 效果",
        "total_records": 3,
        "highest_evidence_level": 4,
    }
]


GEO_MONITOR_RECORDS: list[dict[str, Any]] = [
    {
        "record_id": "geo-rec-p1-mock-001",
        "session_id": "geo-mon-p1-mock-001",
        "query": "武汉智能沙盘厂家有哪些？",
        "ai_channel": "deepseek",
        "target_brand": "武汉微艺达智能科技有限公司",
        "target_url": "https://example.com/wuhan-sandtable-demo",
        "checked_at": "2026-09-09 10:02:00",
        "evidence_level": 2,
        "evidence_label": EVIDENCE_LEVELS["2"],
        "related_concept_found": True,
        "brand_mentioned": True,
        "page_retrieved": False,
        "source_cited": False,
        "raw_response": "Mock response: 回答中提到武汉微艺达，但没有引用目标页面。",
        "response_summary": "品牌被提及，但未确认页面检索或来源引用。",
        "manual_review_status": "待复核",
        "reviewer": "",
        "data_mode": "mock",
    },
    {
        "record_id": "geo-rec-p1-mock-002",
        "session_id": "geo-mon-p1-mock-001",
        "query": "武汉沙盘模型制作公司哪家好？",
        "ai_channel": "doubao",
        "target_brand": "武汉微艺达智能科技有限公司",
        "target_url": "https://example.com/wuhan-sandtable-demo",
        "checked_at": "2026-09-09 10:05:00",
        "evidence_level": 3,
        "evidence_label": EVIDENCE_LEVELS["3"],
        "related_concept_found": True,
        "brand_mentioned": True,
        "page_retrieved": True,
        "source_cited": False,
        "raw_response": "Mock response: 回答中出现目标页面信息，但未作为来源引用。",
        "response_summary": "页面疑似被检索，仍需人工复核。",
        "manual_review_status": "待复核",
        "reviewer": "",
        "data_mode": "mock",
    },
    {
        "record_id": "geo-rec-p1-mock-003",
        "session_id": "geo-mon-p1-mock-001",
        "query": "智能沙盘和普通沙盘有什么区别？",
        "ai_channel": "yuanbao",
        "target_brand": "武汉微艺达智能科技有限公司",
        "target_url": "https://example.com/wuhan-sandtable-demo",
        "checked_at": "2026-09-09 10:08:00",
        "evidence_level": 4,
        "evidence_label": EVIDENCE_LEVELS["4"],
        "related_concept_found": True,
        "brand_mentioned": True,
        "page_retrieved": True,
        "source_cited": True,
        "raw_response": "Mock response: 回答中引用了目标 URL。此记录仅用于 P1 UI 骨架验证。",
        "response_summary": "来源引用示例，真实上线后必须保存原始证据。",
        "manual_review_status": "待复核",
        "reviewer": "",
        "data_mode": "mock",
    },
]
